name: cdk

on:
  release:
    action: released

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Deploy to production CDK
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: cdk-ingest.yaml
          repo: lacework/services
          ref: main
          token: ${{ secrets.RELENG_GH_TOKEN }}
          inputs: '{ "owner": "lacework", "repository": "lacework-vulnerability-scanner", "tag": "${{  github.event.release.tag_name }}" }'
          wait-for-completion: false
